### ISSUE TITLE
M1 Max supported?

### ISSUE THREAD

**Issue by edbarbier** [glonlas/Stable-Diffusion-Apple-Silicon-M1-Install#3]
## Describe your environment

  * Operating system: ____ (`uname -a`)

Monterey 12.5.1
MBP 14" M1 Max 

  * Bash Version:  GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

  * Script Version: 0.1.2
 

## Describe the problem:

*Explain the problem you have encountered*

Post installation, when launching the script, it seems like the script doesn't recognize my CPU as Apple Silicon even though it is.

### Steps to reproduce:

  1. Follow Installation steps.
  2. Run ./install-stable-diffusion-apple-silicon.sh
  
  
### Observed Results:

+-----------------------------------------+
|                                         |
|     Stable Diffusion Apple Silicon      |
|             Install script              |
|                                         |
+-----------------------------------------+
Script Version: 0.1.2
Source of the script: https://github.com/glonlas/Stable-Diffusion-Apple-Silicon-M1-Install
Apple CPU not supported
We are sorry, but this script supports only Apple Silicon CPU (M1, M1Pro, ...)

**Comment by glonlas** [comment]
Good catch!

Could you run the following command please: uname -m

Then paste the output. The CPU might been seen differently that M1

**Comment by edbarbier** [comment]
Sure thing. 

Here is the output: x86_64

**Comment by jjsanderson** [comment]
Do you have Terminal set to 'Open using Rosetta', by any chance? (right-click the Terminal icon in Applications, select Get Info).

**Comment by glonlas** [comment]
To @edbarbier: @jjsanderson is right. Your terminal runs in X86_64 mode instead of arm64. Hence this is why when the script runs `if [[ $(uname -m) != 'arm64' ]]` it cannot detect is it in a arm64 env. 

I will close the ticket for now. Please feel free to re-open it if the error persists once you are on arm64. setup. 

Note: the current install (with the version 0.1.2) is broken. Since the LStein project was rename InvokeAI and includes tons of refactoring this script install does not work anymore. A patch is coming this week.
